base_url = "https://luisvgs.github.io"
title = "Luis' Blog"
theme = "no-style-please"

compile_sass = true
minify_html = true
generate_feed = true
build_search_index = false

[markdown]
highlight_code = true

taxonomies = [
    { name = "tags" },
    { name = "categories" },
]

[extra]
author = "Luis Vegas"
header_nav = [
    { name = "~home", url = "/" },
    { name = "+posts", url = "/posts" },
]
footer_nav = [
    { name = "< previous", url = "#" },
    { name = "webring", url = "#" },
    { name = "next >", url = "#" },
]
